### ISSUE TITLE
build_frequency_count_tables: breakaway no longer supports file paths as inputs

### ISSUE THREAD

**Issue by MathFl** [adw96/breakaway#105]
> R.version
               _                           
platform       x86_64-w64-mingw32          
arch           x86_64                      
os             mingw32                     
system         x86_64, mingw32             
status                                     
major          4                           
minor          0.4                         
year           2021                        
month          02                          
day            15                          
svn rev        80002                       
language       R                           
version.string R version 4.0.4 (2021-02-15)
nickname       Lost Library Book           
> sessionInfo()
R version 4.0.4 (2021-02-15)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

Matrix products: default

locale:
[1] LC_COLLATE=French_Canada.1252  LC_CTYPE=French_Canada.1252    LC_MONETARY=French_Canada.1252
[4] LC_NUMERIC=C                   LC_TIME=French_Canada.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] forcats_0.5.1   stringr_1.4.0   dplyr_1.0.4     purrr_0.3.4     readr_1.4.0     tidyr_1.1.2     tibble_3.1.0   
 [8] ggplot2_3.3.3   tidyverse_1.3.0 magrittr_2.0.1  DivNet_0.3.6    breakaway_4.7.3 phyloseq_1.34.0

loaded via a namespace (and not attached):
 [1] nlme_3.1-152        fs_1.5.0            lubridate_1.7.10    doParallel_1.0.16   progress_1.2.2     
 [6] httr_1.4.2          tools_4.0.4         backports_1.2.1     utf8_1.1.4          R6_2.5.0           
[11] vegan_2.5-7         DBI_1.1.1           BiocGenerics_0.36.0 mgcv_1.8-33         colorspace_2.0-0   
[16] permute_0.9-5       rhdf5filters_1.2.0  ade4_1.7-16         withr_2.4.1         tidyselect_1.1.0   
[21] prettyunits_1.1.1   compiler_4.0.4      cli_2.3.1           rvest_0.3.6         Biobase_2.50.0     
[26] xml2_1.3.2          scales_1.1.1        mvnfast_0.2.5.1     minqa_1.2.4         XVector_0.30.0     
[31] pkgconfig_2.0.3     lme4_1.1-26         dbplyr_2.1.0        rlang_0.4.10        readxl_1.3.1       
[36] rstudioapi_0.13     generics_0.1.0      jsonlite_1.7.2      biomformat_1.18.0   Matrix_1.3-2       
[41] Rcpp_1.0.6          munsell_0.5.0       S4Vectors_0.28.1    Rhdf5lib_1.12.1     fansi_0.4.2        
[46] ape_5.4-1           abind_1.4-5         lifecycle_1.0.0     stringi_1.5.3       MASS_7.3-53        
[51] zlibbioc_1.36.0     rhdf5_2.34.0        plyr_1.8.6          grid_4.0.4          parallel_4.0.4     
[56] crayon_1.4.1        lattice_0.20-41     Biostrings_2.58.0   haven_2.3.1         splines_4.0.4      
[61] multtest_2.46.0     hms_1.0.0           pillar_1.5.1        igraph_1.2.6        boot_1.3-26        
[66] reshape2_1.4.4      codetools_0.2-18    stats4_4.0.4        reprex_1.0.0        glue_1.4.2         
[71] data.table_1.14.0   BiocManager_1.30.10 modelr_0.1.8        vctrs_0.3.6         nloptr_1.2.2.2     
[76] foreach_1.5.1       cellranger_1.1.0    gtable_0.3.0        assertthat_0.2.1    broom_0.7.5        
[81] survival_3.2-7      iterators_1.0.13    IRanges_2.24.1      cluster_2.1.0       statmod_1.4.35     
[86] ellipsis_0.3.1    

Hi Amy,

I have an issue with the build_frequency_count_tables function, the error message is "Error in FUN(newX[, i], ...) : 
  breakaway no longer supports file paths as inputs".

I used to import my data (read.table(data)), then transpose it to have samples in rows (frequency=t(data)), then I do the function.
My data are abundance (not OTU) but I also tried with number of reads per taxa, I still have the same message.
I also tried the first times with oldest R version (3.6.1) and I updated to test if it was the issue.
 I restarted R and reinstalled. I have done:
library(breakaway)
library(phyloseq)
library(magrittr)
library(tidyverse)

I run some examples you gave:
data("toy_otu_table")
build_frequency_count_tables(toy_otu_table)

data("GlobalPatterns")
build_frequency_count_tables(GlobalPatterns)

They are both running correctly but not mine.

Do you know how could I fix it?

Thanks

**Comment by adw96** [comment]
Hi @MathFl  -- thanks for your question! If `df` is the name of your table, can you show me the output of 

```
class(df)
head(df)
apply(df, 2, class)
```

? If I recall correctly, that particular error message only comes up if you try to give breakaway character-valued info, rather than numeric information as it expects.

**Comment by MathFl** [comment]
Hi Amy,

Thank you for your rapid answer.

Indeed the output specify "character" for my samples.
class(data_count_species)
[1] "data.frame"
> head(data_count_species)
                             taxa    Q170001 Q170006      Q170008      Q170013      Q170019     Q170061 Q170067 Q170079
1       Methanobrevibacter_oralis 0.00000000       0 0.0000000000 0.0000000000 0.0000000000 0.000000000       0       0
2            Luteitalea_pratensis 0.00000000       0 0.0000000000 0.0000000000 0.0000000000 0.000000000       0       0
3 Actinobaculum_sp_oral_taxon_183 0.00000000       0 0.0003015854 0.0002332406 0.0000000000 0.001420520       0       0
4        Actinomyces_cardiffensis 0.01012777       0 0.0000000000 0.0124114604 0.0001086095 0.002100231       0       0
5         Actinomyces_denticolens 0.00000000       0 0.0000000000 0.0000000000 0.0000000000 0.000000000       0       0
  Q170094 Q170109 Q170111 Q170115 Q170117 Q170129      Q170146      Q170152 Q170166 Q170172   Q170177     Q170194
1       0       0       0       0       0       0 0.0000000000 0.000000e+00       0       0 0.0000000 0.000000000
2       0       0       0       0       0       0 0.0000000000 0.000000e+00       0       0 0.0000000 0.000000000
3       0       0       0       0       0       0 0.0002638338 0.000000e+00       0       0 0.0000000 0.006055541
4       0       0       0       0       0       0 0.0000000000 9.432071e-05       0       0 0.3745808 0.000000000
5       0       0       0       0       0       0 0.0000000000 0.000000e+00       0       0 0.0000000 0.000000000

> apply(data_count_species, 2, class)
       taxa     Q170001     Q170006     Q170008     Q170013     Q170019     Q170061     Q170067     Q170079     Q170094
"character" "character" "character" "character" "character" "character" "character" "character" "character" "character"

In my table should I indicate my samples names or not? Is that why I have character-valued info? What about the taxa?

Mathilde

________________________________
De : AmyW ***@***.***>
Envoyé : lundi 8 mars 2021 18:11
À : adw96/breakaway ***@***.***>
Cc : Mathilde Flahaut ***@***.***>; Mention ***@***.***>
Objet : Re: [adw96/breakaway] build_frequency_count_tables: breakaway no longer supports file paths as inputs (#105)

[Externe UL*]

Hi @MathFl<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMathFl&data=04%7C01%7Cmathilde.flahaut.1%40ulaval.ca%7C4bba25ac033040ce17b508d8e28bdedf%7C56778bd56a3f4bd3a26593163e4d5bfe%7C1%7C1%7C637508437655019983%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=W2YVTK71qR6JYMtjvti1BmdQ7HEh1gd%2FRDTjo7UQEkM%3D&reserved=0> -- thanks for your question! If df is the name of your table, can you show me the output of

class(df)
head(df)
apply(df, 2, class)


? If I recall correctly, that particular error message only comes up if you try to give breakaway character-valued info, rather than numeric information as it expects.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fadw96%2Fbreakaway%2Fissues%2F105%23issuecomment-793156803&data=04%7C01%7Cmathilde.flahaut.1%40ulaval.ca%7C4bba25ac033040ce17b508d8e28bdedf%7C56778bd56a3f4bd3a26593163e4d5bfe%7C1%7C1%7C637508437655019983%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=0jT0Pwgzy9eaZJtfwwecjWcToEnTB8TRcVWowpU17MU%3D&reserved=0>, or unsubscribe<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FATESVN25SF6A7Z6ZASD342LTCVKTXANCNFSM4Y2JTEPQ&data=04%7C01%7Cmathilde.flahaut.1%40ulaval.ca%7C4bba25ac033040ce17b508d8e28bdedf%7C56778bd56a3f4bd3a26593163e4d5bfe%7C1%7C1%7C637508437655029976%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=27uMxU2%2BkWap2GT5V%2Brs1ubIa3J%2B8L1xZXLeALTITzA%3D&reserved=0>.

*ATTENTION : L’émetteur de ce courriel est externe à l’Université Laval.
Évitez de cliquer sur un hyperlien, d’ouvrir une pièce jointe ou de transmettre des informations si vous ne connaissez pas l’expéditeur du courriel. En cas de doute, contactez l’équipe de soutien informatique de votre unité ou ***@***.***
________________________________

**Comment by adw96** [comment]
Hi Mathilde @MathFl -- I recommend taking a look at the format of `toy_otu_table`. If you can wrangle your data into the same format (no taxon names) you shouldn't have any issues. It also looks like you have values between 0 and 1 -- breakaway requires counts. 

Since this isn't a breakaway problem, I'm going to close this issue.

Amy
