### ISSUE TITLE
Batch effect in alpha and beta diversity

### ISSUE THREAD

**Issue by ari9609** [adw96/breakaway#107]
Hi
I'm trying to solve batch effect problem when analyzing alpha and beta diversity
I understand, breakaway and DivNet attempt to take into account library size, and the basis of betta and betta random functions are linear mixed models (LMM) or hierarchical models.
My question is if it would be correct to set "sequencing batch" as random variable ("groups" option in betta random function), since I have only 2 sequencing batches

**Comment by adw96** [comment]
Yes, I think that "batch" is a perfect use of random effects for modelling alpha & beta diversity! Great work!
