### ISSUE TITLE
Using betta multiple times to account for sub-sampling

### ISSUE THREAD

**Issue by adityabandla** [adw96/breakaway#109]
Hi Amy,

I am working with a dataset that consists of samples collected from two different locations. Within each location, 10 independent samples were collected each from 3 transects. For alpha diversity estimates, I was thinking about pooling information from the 10 samples from each transect and then use these transect-level estimates for the between-location comparison. 

To pool information from the 10 samples from each transect, I used breakaway for each location separately. I then used betta with `X = model.matrix(~transect)` to get transect-level mean estimates and their associated standard errors.

For the between-location comparison, I ran betta with the transect-level mean estimates and SEs from each location, obtained from the previous step `X = model.matrix(~location)`. Is this a valid approach?

Attached is an example of the metadata file I am using.
[metadata.csv](https://github.com/adw96/breakaway/files/7092244/metadata.csv)

**Comment by ailurophilia** [comment]
Hi Aditya,

The approach you consider here is a two-stage regression, if I understand correctly. I think this is probably fine, though you may get somewhat better performance with a one-stage regression -- specifically, a mixed effects regression. You can fit an appropriate mixed effects model using the `betta_random` function with formula `y~location|transect` (you'd still fit breakaway as you currently are to generate input for `betta_random`). Using `betta_random` here amounts to estimating the means at each location while accounting for possible correlation within transect.

I hope this helps!

Best,
David
