### ISSUE TITLE
Kenward-Roger Adjustment in betta(), betta_random()?

### ISSUE THREAD

**Issue by ailurophilia** [adw96/breakaway#113]
In my understanding, both the typical Wald tests and LR tests for fixed effects in general linear models may be fairly anti-conservative in small samples (see, e.g., Welham and Thompson, 1997). There is, however, a method using a fairly simple adjustment to the Wald test (Kenward & Roger 1997) that generally performs better in small to moderate sample sizes and that is already implemented via the R package _pbkrtest_ (Halekoh & Højsgaard 2014). I haven't looked into how easy it would be to use that package within breakaway, but it also doesn't look like just directly implementing the Kenward-Roger adjustment would be too onerous.

In any case, I don't know if this is a priority now, but I wanted to flag it as a fairly self-contained potential mini-project.

__________________________________________________________________________________________________________
Halekoh, Ulrich, and Søren Højsgaard. "A Kenward-Roger approximation and parametric bootstrap methods for tests in linear mixed models the R package pbkrtest." Journal of Statistical Software 59, no. 1 (2014): 1-32.

Kenward, Michael G., and James H. Roger. "Small sample inference for fixed effects from restricted maximum likelihood." Biometrics (1997): 983-997.

Welham, S. J., and R. Thompson. "Likelihood ratio tests for fixed model terms using residual maximum likelihood." Journal of the Royal Statistical Society: Series B (Statistical Methodology) 59, no. 3 (1997): 701-714.

**Comment by adw96** [comment]
That sounds great, @ailurophilia ! I'd be very grateful if you were to take this on and can review a PR on it.
