### ISSUE TITLE
utWLRM and tWLRM

### ISSUE THREAD

**Issue by adw96** [adw96/breakaway#12]
Possible issue with not skipping frequency counts that have value zero in the weighted linear regression model implementations. TODO: test and confirm

**Comment by edward130603** [comment]
Hi Amy, I think it is fine if no cutoff is set. If the user sets a cutoff bigger than first freq count that has value zero, then some of the calculated ratios will involve frequency counts that aren't consecutive.

**Comment by bryandmartin** [comment]
@adw96 Add catch: If length of frequency vector is shorter than cutoff, add a warning message.
