### ISSUE TITLE
Error in setting cutoff in wlrm

### ISSUE THREAD

**Issue by edward130603** [adw96/breakaway#13]
Hi, I noticed that in wlrm, setting cutoff for maximum frequency count to be a number greater than number of rows in dataset throws an error. Thanks!

**Comment by adw96** [comment]
I just checked and I can't reproduce this error, Edward:

wlrm_transformed(apples, cutoff=50000)
wlrm_untransformed(apples, cutoff=50000)

Let me know if you have further problems!
