### ISSUE TITLE
population richness estimates are lower than sample richness estimates

### ISSUE THREAD

**Issue by Jiulong-Zhao** [adw96/breakaway#152]
Hi Amy,
When I tried to run breakaway using my dataset, the population richness estimates calculated by breakaway() are lower than the sample richness estimates calculated by sample_richness(). I wonder if this is reasonable. 
The population richness estimates are as follows：
![image](https://user-images.githubusercontent.com/62932502/165419639-44f0b97f-a435-4268-ba13-af826ab83246.png)
The sample richness estimates are as follows:
`> sample.richness
A collection of 12 alpha diversity estimates:

$ DC6_s_cell
Estimate of richness from method Plug-in:
  Estimate is 18991
 with standard error 0
  Confidence interval: (18991, 18991)

$ E1_s_cell
Estimate of richness from method Plug-in:
  Estimate is 14987
 with standard error 0
  Confidence interval: (14987, 14987)

$ SEATS_s_cell
Estimate of richness from method Plug-in:
  Estimate is 18807
 with standard error 0
  Confidence interval: (18807, 18807)

$ DC6_d_cell
Estimate of richness from method Plug-in:
  Estimate is 14900
 with standard error 0
  Confidence interval: (14900, 14900)

$ E1_d_cell
Estimate of richness from method Plug-in:
  Estimate is 18791
 with standard error 0
  Confidence interval: (18791, 18791)

$ SEATS_d_cell
Estimate of richness from method Plug-in:
  Estimate is 14566
 with standard error 0
  Confidence interval: (14566, 14566)

$ DC6_s_virus
Estimate of richness from method Plug-in:
  Estimate is 18490
 with standard error 0
  Confidence interval: (18490, 18490)

$ E1_s_virus
Estimate of richness from method Plug-in:
  Estimate is 18593
 with standard error 0
  Confidence interval: (18593, 18593)

$ SEATS_s_virus
Estimate of richness from method Plug-in:
  Estimate is 18552
 with standard error 0
  Confidence interval: (18552, 18552)

$ DC6_d_virus
Estimate of richness from method Plug-in:
  Estimate is 15202
 with standard error 0
  Confidence interval: (15202, 15202)

$ E1_d_virus
Estimate of richness from method Plug-in:
  Estimate is 19168
 with standard error 0
  Confidence interval: (19168, 19168)

$ SEATS_d_virus
Estimate of richness from method Plug-in:
  Estimate is 19769
 with standard error 0
  Confidence interval: (19769, 19769)`

My dataset is like this: 
![image](https://user-images.githubusercontent.com/62932502/165420135-993443ac-6754-4443-92d7-c54b9bff61df.png)

Thank you so much!
 
Jiulong

**Comment by adw96** [comment]
Hi Jiulong -- thanks for your question. Something is definitely going wrong -- as you notice, it's not possible to have total diversity greater than sample diversity. 

Thanks for showing me what your data looks like -- this is not a data structure that breakaway can handle. breakaway excepts count data -- the number of times each taxon was observed in each sample. These should be whole numbers, not eg 13.6. Possibly your data are coverages -- can you convert them to recruited reads if so?

I hope that helps -- I'm going to close this issue because it's a data structures issue rather than a breakaway issue :)
