### ISSUE TITLE
error when using the function build_frequency_count_tables ()

### ISSUE THREAD

**Issue by fadwaMeh** [adw96/breakaway#153]
Hi all,

I am working on alpha diversity of gut samples. I encounter a problem when using the function build_frequency_count_tables of breakaway and i'm not able to find a solution. i get this error message when i run build_frequency_count_tables(data) : 
Erreur dans FUN(newX[, i], ...) : 
  breakaway no longer supports file paths as inputs

it says that my input is a file path but it's not, i do give a data frame. Here is my code  entirely : 
cov_table <- read.csv("contig_coverage.csv", sep = '\t', header = TRUE, check.names = FALSE)
cov_table = data.frame(cov_table, check.names = FALSE)
is.data.frame(cov_table)
freq_table = build_frequency_count_tables(t(cov_table))

when i run the is.data.frame(cov_table_nun), i get a TRUE answer so I can't find a way to fix the problem.
Any advice are highly appreciated!!!

Here attached the output of R as suggested in the instruction post:
library(breakaway)
library(ggplot2)
library(forcats)
library(vegan)
library(ggpubr)
library(reshape2)
library(viridis)
library(RColorBrewer)
R.version
-
platform       x86_64-apple-darwin17.0     
arch           x86_64                      
os             darwin17.0                  
system         x86_64, darwin17.0          
status                                     
major          4                           
minor          1.3                         
year           2022                        
month          03                          
day            10                          
svn rev        81868                       
language       R                           
version.string R version 4.1.3 (2022-03-10)
nickname       One Push-Up

**Comment by ailurophilia** [comment]
Hi – thanks for bringing this to our attention! I'm looking into the behavior of `build_frequency_count_tables`, so I may have a more detailed answer in the next few days, but in the meantime, I highly recommend looking at cov_table – what do entries of the cov_table look like if you run `head(cov_table)` or `View(cov_table)`? This may provide the most useful information.

**Comment by ailurophilia** [comment]
Short follow-up: it looks like the `convert` function in breakaway (which `build_frequency_count_tables` calls) may throw this error if it is fed a character vector. Have you checked that the columns `t(cov_table)` are numeric vectors and not character vectors? Thanks!

**Comment by adw96** [comment]
Closing this issue -- conclusion is that we think that there are characters in the data given to `build_frequency_count_tables`. Thanks for checking in and let us know if you have other questions, @fadwaMeh !
