### ISSUE TITLE
kicked off CRAN, grrrr

### ISSUE THREAD

**Issue by adw96** [adw96/breakaway#166]
corncob got kicked off CRAN, so breakaway had warnings, but Bryan fixed the corncob issues and breakaway stopped having warnings, but we got kicked off anyway?!?!?! (Just providing some background here for anyone who thinks that dealing with CRAN is easy)

Working on getting back up on CRAN ASAP

**Comment by paulinetrinh** [comment]
@adw96 Issues #167, #168, and #169 were addressed. R-CMD-Check now returns 0 errors, 0 warnings, and 0 notes. Please let us know if you'd like us to move forward with submitting this to CRAN or if you'd like to review and submit yourself!

**Comment by paulinetrinh** [comment]
`R CMD check --as-cran` log: 

[00check.log](https://github.com/adw96/breakaway/files/9711531/00check.log)

There is 1 note `checking CRAN incoming feasibility ... NOTE` that I'm not sure how to resolve (or if we need to?).

**Comment by svteichman** [comment]
I wonder if we can add a note that we've checked all of the urls and they are correct (something like the note they provide [here](https://rdrr.io/github/jepusto/SingleCaseES/f/cran-comments.md)). I double-checked and all of these links are valid.

**Comment by adw96** [comment]
Update for everyone following - we have resubmitted and hope to be back up within a couple of days at most. I am very grateful to @svteichman and @paulinetrinh for fixing these issues -- please join me in thanking them for their prompt hard work! 🙌

**Comment by adw96** [comment]
@paulinetrinh @svteichman can we close this?

**Comment by svteichman** [comment]
Closing because breakaway is back on cran!
