### ISSUE TITLE
CRAN issues: internals from lme4

### ISSUE THREAD

**Issue by adw96** [adw96/breakaway#167]
Currently we use 

```
  if (!is.null(formula)) {
    ses <- data[,deparse(substitute(ses))]
    group_var <- lme4:::barnames(lme4::findbars(lme4:::RHSForm(formula)))
    groups <- data[,group_var]
    full_form <- lme4::subbars(formula)
    sm_form <- update(full_form, paste("~.-",group_var))
    X <- stats::model.matrix(sm_form, data)
    chats <- stats::model.response(stats::model.frame(formula = sm_form, data = data))
  }
```

in `model_betta_random.R`. We need a new alternative that doesn't use ::: calls to get back on CRAN. So 

- `lme4:::barnames`
- `lme4:::RHSForm`

need new versions. 

Can I please have some support on this in the next week @MariaAVC @svteichman? 🙏

**Comment by svteichman** [comment]
Addressed in pull requests #170 and #171
