### ISSUE TITLE
 checking for unstated dependencies in vignettes ... NOTE

### ISSUE THREAD

**Issue by adw96** [adw96/breakaway#168]
From a `R CMD check breakaway_4.8.0.tar.gz --as-cran `

* checking for unstated dependencies in vignettes ... NOTE
'::' or ':::' import not declared from: ‘dplyr’
'library' or 'require' call not declared from: ‘remotes’

I can't remember what the magic combination of Imports/Suggests/roxygen `@import`/@importFrom give, but we are also having issues with this. Would someone be able to help? In `vignettes/diversity-hypothesis-testing.Rmd` we use `dplyr::left_join`, e.g.

I may have fixed this but I'm not sure. Flagging for help.

**Comment by svteichman** [comment]
Addressed in pull requests #170 and #171
