### ISSUE TITLE
Request: Adjust p-value digits 

### ISSUE THREAD

**Issue by kunstner** [adw96/breakaway#172]
Hi,
is it possible to implement a parameter for the betta/betta_random function to adjust for the number of digits for the p-values? The default values are sometime not sufficient. So far, I adjusted the code myself but I think I'm not the only one having this issue.
Best,
 Axel

**Comment by adw96** [comment]
Thanks @kunstner -- this is a reasonable request, thanks! We will work on it and get back to you.

**Comment by svteichman** [comment]
This has been addressed with pull request #176 .

**Comment by adw96** [comment]
@kunstner thanks again for the great request and please let us know if you have any follow-up questions
