### ISSUE TITLE
Error in data[1:(cutoff - 1), 1] : incorrect number of dimensions

### ISSUE THREAD

**Issue by adw96** [adw96/breakaway#18]
`y <- cbind(c(1,3,5,6,11,13,17,21), c(13,2,2,3,2,1,1,2))`
`y`
`chao_bunge(y)`

**Comment by adw96** [comment]
This generally fits in with the noncontiguous frequency count problem. tests should be written to catch this for chao_bunge, breakaway, wlrm's....

**Comment by adw96** [comment]
> chao_bunge(y)
Estimate of richness from method Chao-Bunge:
  Estimate is NA with standard error NA
  Confidence interval: (NA, NA)
  Cutoff:  6

No error is thrown, this is reasonable, but again fits in with noncontiguous problem.

**Comment by cjburgess** [comment]
Are there any work around with this error? I am currently getting this error for one of my fungal samples. 

```
freq = c(2, 4, 5, 6, 7, 8, 9, 10, 12, 13, 14, 15, 16, 17, 18, 19, 21, 22, 23, 24, 25, 34, 38, 42, 43, 55, 57, 59, 70, 72, 73, 80, 89, 93, 94, 96, 100, 111, 139, 149, 188, 232, 254, 295, 366, 436, 509, 551, 1296, 1450, 1777, 1836, 2324, 2643, 6468)
counts = c(5, 7, 7, 7, 5, 6, 1, 2, 2, 4, 2, 4, 2, 1, 4, 1, 1, 3, 1, 1, 1, 2, 1, 2, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1)
x = cbind(freq, counts)
breakaway_nof1(x)
```

Adding a `freq= 3` and `count= 1` row does fix the issue but definitely not an ideal solution.

**Comment by adw96** [comment]
@cjburgess  Thanks for flagging this with me! I never know what folks need unless I'm told 👍 

This is actually related to #55 . I pasted your example there and plan to work on it today. If you want to subscribe to that thread you'll be notified when it's resolved 😸 

Cheers,

Amy
