### ISSUE TITLE
Parameter "initial_est" in betta function

### ISSUE THREAD

**Issue by Vlasovets** [adw96/breakaway#192]
Dear Amy,

I was wondering if you could navigate me with a proper choice of  "initial_est" parameter in betta function?

`betta = breakaway.betta(chats=es, ses=er, X=x)
`
Before I was using  default NULL value, and it worked well for 90 samples, now I have 500 and the function throws me the [error](https://github.com/adw96/breakaway/blob/main/R/model_betta.R):
```
R[write to console]: Error in (function (chats = NULL, ses, X = NULL, initial_est = NULL, formula = NULL,  : 
  The starting value and 200 perturbations were not enough to find a maximum likelihood solution. Please try again with a new choice of `initial_est`.
```

I looked at the code and I understood that the initial_est are the estimated parameters of Gaussian, following the error hint, should I fit some other distribution?

I was wondering if it is somehow possible to let the user to increase the number of pertubations? 
maybe in my case, the process hasn't converged due to the bigger number of samples.

I'm using breakaway in Python with rpy2 interface, but here is the info of R session:
platform       x86_64-pc-linux-gnu         
arch           x86_64                      
os             linux-gnu                   
system         x86_64, linux-gnu                                      
language       R                           
version.string R version 4.3.0 (2023-04-21)

Thank you for your time!
Oleg

**Comment by Vlasovets** [comment]
found proper Gaussian parameters as described above.

**Comment by adw96** [comment]
Amazing, thanks so much for closing!
