### ISSUE TITLE
Model selection from betta_random() using AIC or alternatives

### ISSUE THREAD

**Issue by ivanllampy** [adw96/breakaway#193]
Hello,

Thank you for providing a nice R package with clear tutorials.

I have been using betta() and betta_random() for estimating alpha diversity of a bacterial 16S metabardocing dataset.
I notice AIC and AICc are calculated in betta() for model comparison, but not in betta_random().

I tried to calculate AIC by myself for models from betta_random(), but full of doubt.
May I ask is there any method to calculate AIC or AICc for betta_random()?
Alternatively, are there any recommended method for model comparisons?

Any help would be highly appreciated.
Thank you!

Best wishes

**Comment by adw96** [comment]
Yes, this is definitely possible! 

@MariaAVC could I ask your help implementing this for @ivanllampy ? 🙏

**Comment by MariaAVC** [comment]
Hello @adw96 and @ivanllampy. This was addressed in the last merge! I hope it is useful :) 

Best wishes
