### ISSUE TITLE
betta_random question

### ISSUE THREAD

**Issue by ntromas** [adw96/breakaway#199]
Hi Amy and Breakaway team!

This is a very naive question but is there a way to use multiple random variables with betta_random?

Cheers!

Nico

**Comment by svteichman** [comment]
Hi Nico, 

By "use multiple random variables", are you talking about the random effects in `betta_random`? I'm interpreting your question as the following: you have data with `variable 1` and `variable 2`, and you would like to use the information in both of these variables to define groups for random effects. If so, then I would recommend making a new variable in your data frame, `variable 3`, in which you combine the information in `variable 1` and `variable 2`, for example if you have day and month, create a new data_month variable. Then you can use `variable 3` for grouping. Please let me know if this isn't the question that you're asking!

Best,
Sarah

**Comment by ntromas** [comment]
Hi Sarah,

Thanks for the answer! I will try this option!

Cheers,

Nico
