### ISSUE TITLE
Breakaway test fails due to NA estimates

### ISSUE THREAD

**Issue by bryandmartin** [adw96/breakaway#23]
In test-alpha_estimates.R:

```test_that("alpha_estimates is robust across taxonomy", {
  
  ## this one
  expect_silent({y <- GlobalPatterns %>% 
    subset_samples(SampleType %in% c("Mock")) %>%
    tax_glom("Phylum") %>%
    breakaway})
  
  expect_is(y, "alpha_estimates")
  expect_is(summary(y), "tbl")
  expect_is(plot(y), "ggplot")
}
```
The y object has all NA estimates, so it breaks the plotting test. Temporarily replaced ```breakaway``` with ```sample_richness``` in the test.

**Comment by adw96** [comment]
@adw96

Need to change breakaway to make it more robust. Move breakaway into function kemp then have breakaway do nested search for reasonable models (CatchAll style, ergh).
