### ISSUE TITLE
alpha_estimates & phyloseq

### ISSUE THREAD

**Issue by adw96** [adw96/breakaway#28]
It would be great to have the names of the samples embedded in the alpha_estimates object if it is created from a phyloseq object. TODO(Amy)

**Comment by adw96** [comment]
This is a duplicate of adw96/DivNet#11 --  it should be on the breakaway forum not the DivNet  forum

**Comment by adw96** [comment]
@bryandmartin I'm working on this now

**Comment by adw96** [comment]
@bryandmartin 
Hey Bryan -- can we write a wrapper for the code 

```
if (class(input_data) == "phyloseq") {
    if (input_data %>% otu_table %>% taxa_are_rows) {
      return(input_data %>% 
               get_taxa %>%
               apply(2, function(x) chao1(make_frequency_count_table(x))) %>%
               alpha_estimates)
    } else {
      return(input_data %>% 
               otu_table %>%
               apply(1, function(x) chao1(make_frequency_count_table(x))) %>%
               alpha_estimates)
    }
  }
```

i.e. a `physeq_wrap <- function(fn, physeq)` This would make this easier

**Comment by bryandmartin** [comment]
ecaee5a

@adw96

**Comment by bryandmartin** [comment]
79b54f06e1645f760f6f1cb807ba8da6cfc31644

**Comment by adw96** [comment]
e.g.

`names(my_a_ests) <-  GlobalPatterns %>% sample_names`
