### ISSUE TITLE
simplify use of betta()

### ISSUE THREAD

**Issue by adw96** [adw96/breakaway#29]
Use alpha_estimates class in betta:

Currently to run:

bt <- betta(summary(ba)$estimate,
summary(ba)$error,
DivNet::make_design_matrix(water, "SampleType"))
bt$table

ideally could run
betta(ba, water, "SampleType") to get the same output

Opened in https://github.com/adw96/stamps2018/issues/23

**Comment by adw96** [comment]
And also tutorial on how to make matrix

**Comment by adw96** [comment]
Hey @bryandmartin -- do you think we could have the option in `betta` to use `lm`-like input for the model? Would you mind taking a look and seeing if this can be as nice to use as `corncob`? 

Cheers!

**Comment by adw96** [comment]
@svteichman Has this been addressed by your ability to hand over a formula to `betta()`? If so, could you please show an example of how you might run `betta()` in a streamlined way using a formula, and then close this issue? Thanks!!!

**Comment by svteichman** [comment]
Yes, I believe it has been! See the vignette `diversity-hypothesis-testing.Rmd` for a more in-depth view of using `betta()` with the formula argument. In the example from above, if `ba` is the output from running breakaway on a dataset, `water` is a phyloseq object and `SampleType` is your covariate of interest as in this issue, you could do the following: 
```
meta <- water %>% sample_data %>% as.tibble %>% mutate("sample_names" = subset_soil %>% sample_names) 
combined <- meta %>% left_join(summary(ba), by = "sample_names")
betta(formula = estimate ~ SampleType, ses = error, data = combined)
```
