### ISSUE TITLE
NaN Value for breakaway error and breakaway_nof1 estimate

### ISSUE THREAD

**Issue by dmuratore** [adw96/breakaway#33]
Howdy! Leaving the process I did to get NaNs for breakaway's error and breakaway_nof1's estimate+error in a little script. Thanks so much for taking a look.

[breakaway_na_ex.txt](https://github.com/adw96/breakaway/files/2255835/breakaway_na_ex.txt)

**Comment by adw96** [comment]
I just ran this script, and breakaway() appears to work fine. Changes we've made in the last 24h would have made this possible, so if you run

`devtools::install_github("adw96/breakaway"); library(breakaway)`

it should work for you. You'll need to see breakaway_4.6.1 in the output of `sessionInfo()`

Does that help?

**Comment by adw96** [comment]
`breakaway_nof1()` is a different story -- let me get back to you on that one

**Comment by adw96** [comment]
There's not enough data to throw out singletons in this study -- yes, it should be NAs for estimates from `breakaway_nof1`. Happy to explain further, but I recommend `breakaway`.

**Comment by dmuratore** [comment]
That definitely solved it, thanks so much! I just took a look at the arxiv description and think I understand breakaway_nof1 but would definitely like to go over it if there's time

**Comment by adw96** [comment]
Happy to go over it!
