### ISSUE TITLE
check_format(output_data) error

### ISSUE THREAD

**Issue by paulinetrinh** [adw96/breakaway#45]
Error in check_format(output_data) :
  Input data to `check_format` is of length 1 or 0.
Calls: summary ... FUN -> breakaway.default -> convert -> check_format

**Comment by adw96** [comment]
Can you give me some details on output data? `head(output_data)`? `class(output_data)`?

**Comment by paulinetrinh** [comment]
Looking at tools_convert.R, I don't think output_data is getting generated by the convert function to be passed through to check_format(). I tried applying convert to the phyloseq input data and no output_data was generated. Because of the unsupported input type issue. 

The class(input_data) is: 
```
[1] "otu_table"
attr(,"package")
[1] "phyloseq"
```
The head(input_data) is a phyloseq object with just the OTU table: 
<img width="637" alt="screen shot 2018-08-15 at 11 13 29 am" src="https://user-images.githubusercontent.com/38084840/44164950-48a59480-a07c-11e8-93dc-d027faf1285a.png">

**Comment by paulinetrinh** [comment]
I retract what I said. Give me a moment to be more helpful.

**Comment by adw96** [comment]
I splice a lot of `print(output_data)`'s into my local version. It will output what it's trying to run the function on into the log file.

Alternatively, you can open up a local script and walk through the code using the Debug frameowrk in RStudio:
https://support.rstudio.com/hc/en-us/articles/205612627-Debugging-with-RStudio#stopping-when-an-error-occurs

**Comment by paulinetrinh** [comment]
Okay that was very useful. The problem is that the input_data file of frequency counts is filled with all 0's. I don't know why though!

**Comment by adw96** [comment]
Need to fix 

`breakaway(c(0,0,0,0))`
