### ISSUE TITLE
Cutoff warning with breakaway

### ISSUE THREAD

**Issue by nmshahir** [adw96/breakaway#50]
Hello Amy,

I was doing the tutorial seen [here](https://github.com/adw96/stamps2018/blob/master/estimation/diversity-lab.R) with breakaway as well as applying it to own data.
In both cases, the breakaway command gives me the following warning
```
In cutoff_wrap(my_data, requested = cutoff) :
  ignoring requested cutoff; it's too low
```

Consequently, when I try to plot the breakaway object, I get the follow error
`Error: Aesthetics must be either length 1 or the same as the data (11): x, y, colour, shape`

I can still run betta() on the breakaway object but plotting directly seems to not work?
Help??

Best,
Nur

**Comment by adw96** [comment]
Thanks for alerting us to this Nur. We just fixed this with commit 1d71024. I'm going to close this issue; please reopen if you continue to have problems.

**Comment by nmshahir** [comment]
I think something went wrong
`plot(ba, water, color = "SampleType")`
results in this
![image](https://user-images.githubusercontent.com/4574002/44427527-d3483100-a55f-11e8-8f55-ab313b259d37.png)

**Comment by adw96** [comment]
What's wrong with that?

**Comment by nmshahir** [comment]
this is from the GlobalPatterns dataset and it seems a bit odd to have such large error bars?
Or it that just due to trying to estimate richness based on the underlying ecological network?

**Comment by adw96** [comment]
No, estimating the number of unobserved species is a really challenging statistical problem, and so there is a lot of uncertainty in the estimate. This is actually how uncertain we are about rare taxa. Fortunately you can still do hypothesis testing and find signals in the data because betta() uses information from multiple estimates.

**Comment by nmshahir** [comment]
Okay that makes sense! Thank you!
