### ISSUE TITLE
Change Output Ordering of summary(breakaway(phyloseqobject))

### ISSUE THREAD

**Issue by paulinetrinh** [adw96/breakaway#51]
Switch sample_names over to the first column: 

sample_names    estimate    error    lower    upper    name    model

**Comment by paulinetrinh** [comment]
[alpha-diversity.txt](https://github.com/adw96/breakaway/files/2315898/alpha-diversity.txt)

**Comment by adw96** [comment]
moved to statdivlab/q2-breakaway
