### ISSUE TITLE
using multiple covariates with betta()

### ISSUE THREAD

**Issue by nmshahir** [adw96/breakaway#53]
Hello, 
Quick question, is it possible to use betta() with multiple covariates and if so, how?
-N

**Comment by adw96** [comment]
Yes -- it's easiest to do using `model.matrix` to turn the covariate info into a matrix. Line 269 of [this tutorial](https://github.com/adw96/stamps/blob/master/alphadiversitylab.R) gives a (slightly overcomplicated) example.
