### ISSUE TITLE
Error in alpha_estimate(estimate = diversity, error = diversity_se, estimand = "richness",  :    object 'f0' not found

### ISSUE THREAD

**Issue by RimaChakaroun** [adw96/breakaway#54]
Hey awesome breakaway crew, 

I m running breakaway on my own data and I ve come an error I can't really figure out. 
running `breakaway(ps2)` returns

> Error in alpha_estimate(estimate = diversity, error = diversity_se, estimand = "richness",  : 
  object 'f0' not found
this doesn't happen if I use a preloaded dataset from phyloseq like Gobalpatterns . 

this is my Phyloseq object 
`ps2`

> phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 3013 taxa and 292 samples ]
sample_data() Sample Data:       [ 292 samples by 43 sample variables ]
tax_table()   Taxonomy Table:    [ 3013 taxa by 8 taxonomic ranks ]
phy_tree()    Phylogenetic Tree: [ 3013 tips and 2977 internal nodes ]

thanks for the help and greetings from Germany :) 
Rima

**Comment by adw96** [comment]
Hi Rima! Unfortunately I can't reproduce the error with the given information. Can you show me the frequency count table that broke `breakaway`? i.e. which otu_table sample was the problem, and what are the observed frequencies?

**Comment by adw96** [comment]
Feel free to reopen, @RimaChakaroun ! We are happy to help. #63 gives a good example of how to give us what we need to debug the error.
