### ISSUE TITLE
betta() output "ssq_u"

### ISSUE THREAD

**Issue by PVa-Pe** [adw96/breakaway#61]
Hi, 
I have been playing around with the Breakaway package and I think I am slowly geting the grasp of it. However, I when it comes to the output of the beta() model, I can't get my head around the results$ssq_u value.
I assume is testing the heterogeinity of the groups; can I get a significant value from it? I am not sure how to interprete this.

Thank You,
Paula

**Comment by adw96** [comment]
Hi Paula! Yes, this is the estimate of sigma^2_u which is the "variance unexplained" parameter. The first element of `results$homogeneity` contains the test statistic for the hypothesis that sigma^2_u equals zero, and the second element is the p-value for this hypothesis test. If you're interested in whether or not sites are homogeneous with respect to diversity, here's how you might describe your finding a paper if the p-value is small:

"We find evidence that sampled sites are heterogeneous with respect to diversity (estimated sigma^2_u = ..., p = [small], [citation for paper])"

Or if the p-value is large:

"The variables [...] are sufficient to explain the observed variation in diversity (estimated sigma^2_u = ..., p = [large], [citation for paper])"

While every environment is different, we more often observe diversity to be heterogeneous, even after accounting for measured variables. Microbiomes are pretty different from each other, in my experience!

Hope that helps -- feel free to reopen if you have more questions. 

Amy
