### ISSUE TITLE
Questions regarding singletons

### ISSUE THREAD

**Issue by mestaki** [adw96/breakaway#62]
Hey folks,
I'm just gearing up to finally give Breakaway a go (woo) and am looking for some clarification. I understand it's important to not discard singletons for proper diversity estimation, as per the q2-breakaway tutorial:

> We recommend using a FeatureTable that has been generated from deblur/vsearch or dada2 in R with pool = TRUE to make sure that singletons have not been completely filtered out

I understand denoising pooled reads is more sensitive to rare ASVs and should be used but it comes at quite the computation cost so I'm just wondering if this has been tested and is in fact necessary in the case of paired-end reads. I ask because running DADA2 on paired-end reads still produces singletons since it removes singletons before merging and post-merge singletons are still possible and are not removed as they are considered true ASVs. Would these be adequate for breakaway's estimation models? 
edit: What about 'psuedo-pooling' option of DADA2, might be a good compromise as well?

Also worth mentioning, q2-deblur's default parameters also removes rare features so it might be worth clarifying to manually adjust those parameters in future tutorials?

> --p-min-reads INTEGER           Retain only features appearing at least
>                                   min_reads times across all samples in the
>                                   resulting feature table.  [default: 10]
>   --p-min-size INTEGER            In each sample, discard all features with an
>                                   abundance less than min_size.  [default: 2]

Thanks!

**Comment by adw96** [comment]
Hi Bod @mestaki ! 

`breakaway` should be able to handle both situations, but it's important to keep in mind that the estimates are based on the structure of rare taxa. Therefore, if there are rare taxa that are unreliable or questionable, the breakaway will overestimate the total species richness. This is why clever denoising methods like DADA2 make breakaway more reliable.

I think that pooling and filtering reads are context dependent. Essentially you should aim to produce a ASV table that accurately reflects the number of times each read was observed in each sample. Garbage in = garbage out.

If there are no singletons observed in the dataset, breakaway is unreliable, but indeed as you say, DADA2 ASV tables have singletons in each sample, just not "global singletons" (singletons observed only once in the whole dataset).

My recommendation would be, as with all things bioinformatics, that you try multiple different ways of filtering out low-quality/abundance sequences, and confirm that your results are not overly sensitive to your choices. I know that's more computationally expensive than choosing one way and running with it, but better science results.

Does that answer all of your questions?
  
@paulinetrinh -- do you think we could update the q2-breakaway documentation to include some comments on this?

**Comment by paulinetrinh** [comment]
I'm on it!

**Comment by mestaki** [comment]
Hi @adw96 ,
Thanks for the thorough explanation. In re-reading my original question it seems like such a silly question now that I've properly read the documentations for dada2 and breakaway and actually played around with those parameters a bit. To clarify for others that may be reading this, the singletons that are produced by pairing merged reads in dada2 are not really useful singletons per se, since the real singletons are still discarded after denoising each set of reads (Forward, Reverse). Those remaining singletons are only formed because of the merging process and not really enough to give breakaway's model a proper structure. For the last few projects I've worked on I have been using pooled=TRUE.  I've never tried the psuedo option, but I'm guessing it will be somewhere in between pooling and not pooling. But since this is to be DADA2's default setting in the future releases, it may be worth comparing. I am convinced that pooling is still a better choice however.
Thanks again.
