### ISSUE TITLE
betta() output

### ISSUE THREAD

**Issue by liisaveerus** [adw96/breakaway#66]
Hi Amy,

Thanks so much for uploading a vignette on hypothesis testing with betta() and betta_random(). I posted a reply to my previous issue [#31](https://github.com/adw96/DivNet/issues/31) under DivNet and realised that it is better suited here:

The betta_random() works like a charm, according to your shared vignette. Just one question about the output.

results <- betta_random(chats = estimated_richness$estimate,
ses = estimated_richness$error,
X = model.matrix(~**Organ*Health.Status**, data = estimated_richness),
groups=estimated_richness$Individual.ID)

For clarification:
Organ: heart, liver, lung, kidney
Health.Status: healthy, symptomatic

<img width="411" alt="Example" src="https://user-images.githubusercontent.com/52078155/63432353-eadb2380-c418-11e9-90e1-808e8eb3f91a.PNG">

Are the first estimates for healthy organs and then the Health.Status:Symptomatic is for heart*symptomatic?

What about the following function and output? Are the health status (healthy) and age (0.5 weeks) incorporated in the intercept (organ=heart)?

results <- betta_random(chats = estimated_richness$estimate,
                                       ses = estimated_richness$error,
                                       X = model.matrix(~**Organ+Health.Status+as.factor(Age)**, data = estimated_richness), groups=estimated_richness$Individual.ID) 

For clarification:
Organ: heart, liver, lung, kidney
Health.Status: healthy, symptomatic
Age: 0.5, 1, 2, 3 weeks

<img width="397" alt="Example1" src="https://user-images.githubusercontent.com/52078155/63432778-af8d2480-c419-11e9-92c0-7a3de66ba3bc.PNG">

Thanks again!

**Comment by adw96** [comment]
See [here](https://github.com/adw96/DivNet/issues/34) for the interpretation of the first output. For the second, here's the interpretation of the parameter estimates:

- The "intercept" is the estimated richness in healthy Heart samples at age 0.5 (153 taxa)
- The estimated richness in healthy Liver samples at age 0.5 is 153+61 taxa (61 more taxa estimated to be in Liver samples than in Heart samples at age 0.5)
- The estimated increase in richness in symptomatic samples of any kind is over healthy samples is 15 *fewer* taxa
- The estimated increase in richness for age 1 is 25 taxa for samples of any kind and health status

Essentially to get the estimated richness for a organ, disease status and age, you add up all of the terms that are relevant. Every estimate has the intercept, and addititve factors for health status, organ, and age
