### ISSUE TITLE
Error: non-finite value supplied by optim

### ISSUE THREAD

**Issue by sminot** [adw96/breakaway#71]
I found an odd error where `breakaway::betta` returns the following error for specific values of inputs:

```
Error in optim(mystart, likelihood, hessian = FALSE, control = list(fnscale = -1),  :
  non-finite value supplied by optim
```

### Reproducing the error 

I reproduced the error with the following commands:

```
library(breakaway)
breakaway::betta(chats=c(-0.013892611956319358, 0.00809696161789718, 0.005459268094084673), ses=c(0.012075830274043914, 0.00429604108003701, 0.0067910218651793496))
```

NOTE: The error does _not_ occur when I remove a single digit from the end of one value, i.e.

```
breakaway::betta(chats=c(-0.013892611956319358, 0.00809696161789718, 0.005459268094084673), ses=c(0.012075830274043914, 0.00429604108003701, 0.006791021865179349))
```

### Execution Environment

I reproduced this error using the docker container `quay.io/fhcrc-microbiome/breakaway@sha256:1fd7b9e92ac8e2b4a17b7794b816e9b4bb60db410277a2bed3edbe4a88682e22`

### Low Urgency

Because this bug can be avoided by changing the input value extremely slightly, I wouldn't describe this as extremely high urgency.

**Comment by adw96** [comment]
Thanks so much for bringing this to our attention,  @sminot ! Version 4.6.14 addresses this issue, and has a slightly more robust solution that should affect similar datasets. There is also a more informative error message in the event that no MLE can be found. Please give me updated if you find other datasets and I can investigate other initialisations to improve the stability of the estimates.
