### ISSUE TITLE
No "blupses" output by betta

### ISSUE THREAD

**Issue by mooreryan** [adw96/breakaway#72]
Quick question....I'm not getting any `blupses` output when I run the `betta` function.

I'm guessing the issue is that `getvar` is failing for some reason (as in this test is false: https://github.com/adw96/breakaway/blob/e81c91b9628afc5c5e1646e9a359d6cebfa70a9c/R/model_betta.R#L170)

I'm on version 4.6.11 now.  Here is an example of what I mean.

```r
library(tidyverse)
library(breakaway)
library(magrittr)
library(phyloseq)

data(Lee)

meta <- Lee %>% 
  sample_data %>% 
  as_tibble %>% 
  mutate(sample_names = Lee %>% sample_names)

richness_Lee <- Lee %>% breakaway

combined_richness <- meta %>% 
  left_join(summary(richness_Lee),
            by = "sample_names")

betta_char_fixed <- betta(chats = combined_richness$estimate,
                          ses = combined_richness$error,
                          X = model.matrix(~char, data = combined_richness))
```

Is it common to get no `blupses`?  I tried a few other datasets and didn't get them either.

**Comment by adw96** [comment]
Ok -- a new, more defensive programming strategy that always returns `blupses` is now available in v4.6.12. Thank you for letting me know about this issue, @mooreryan. As always, feel free to follow up with any questions and *thank you* for your great feedback and questions.
