### ISSUE TITLE
V 4.6.14 installation errors

### ISSUE THREAD

**Issue by dougwyu** [adw96/breakaway#73]
multiple installation and post-installation errors (3 shown  below)
I'm using clang 7.0.0 and gfortran 6.1

`vignette("intro-diversity-estimation")`
> Warning message:
> vignette ‘intro-diversity-estimation’ not found
 
`frequencytablelist <- build_frequency_count_tables(otu_data)`
> Error in build_frequency_count_tables(otu_data) : 
>   could not find function "build_frequency_count_tables"

`devtools::install_github("adw96/breakaway")`
> Downloading GitHub repo adw96/breakaway@master
> Skipping 1 packages not available: phyloseq
> ✔  checking for file ‘/private/var/folders/4g/4wpmdzbd7tj0cwctcd99wz680000gp/T/RtmpJfc9KK/remotes6b7141af38a5/adw96-breakaway-1c1215c/DESCRIPTION’ ...
> ─  preparing ‘breakaway’:
> ✔  checking DESCRIPTION meta-information ...
> ─  excluding invalid files
>    Subdirectory 'R' contains invalid file names:
>      ‘.-package.R’
> ─  checking for LF line-endings in source and make files and shell scripts
> ─  checking for empty or unneeded directories
> ─  looking to see if a ‘data/datalist’ file should be added
> ─  building ‘breakaway_4.6.14.tar.gz’
>    
> * installing *source* package ‘breakaway’ ...
> ** using staged installation
> ** R
> ** data
> *** moving datasets to lazyload DB
> ** byte-compile and prepare package for lazy loading
> ** help
> *** installing help indices
> *** copying figures
> ** building package indices
> ** installing vignettes
> ** testing if installed package can be loaded from temporary location
> ** testing if installed package can be loaded from final location
> ** testing if installed package keeps a record of temporary installation path
> * DONE (breakaway)

**Comment by adw96** [comment]
Dear @dougwyu ,

I will need you to clarify your question for me. From the order that you have shown, it looks to me like you tried to load the vignette and a breakaway function *before* installing the package. Could you please clarify what your issue is?

**Comment by dougwyu** [comment]
the command order shown wasn't the order run. after installation, i couldn't run two commands in the online vignette (and so i stopped trying). When posting these issues, i thought i would also include the messages from installation (since there is an apparent error message in here too:)

> Subdirectory 'R' contains invalid file names:
> ‘.-package.R’

**Comment by adw96** [comment]
Dear @dougwyu ,

I cannot reproduce your error. The following code works fine for me:

```
sessionInfo()
install.packages("devtools")
devtools::install_github("adw96/breakaway", force=TRUE, build_vignettes = TRUE)
library(breakaway)
vignette("intro-diversity-estimation")
data("toy_otu_table")
build_frequency_count_tables(toy_otu_table)
```

I hope this helps. If you choose to reopen this issue, please provide your session information, and all of the commands that you ran in the order that you ran them. 

Sincerely,

Amy

**Comment by dougwyu** [comment]
`sessionInfo()`
> R version 3.6.1 (2019-07-05)
> Platform: x86_64-apple-darwin15.6.0 (64-bit)
> Running under: macOS Mojave 10.14.6
> 
> Matrix products: default
> BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
> LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib
> 
> locale:
> [1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
>  [1] roxygen2_7.0.1   forcats_0.4.0    stringr_1.4.0    dplyr_0.8.3      purrr_0.3.3     
>  [6] readr_1.3.1      tidyr_1.0.0      tibble_2.1.3     ggplot2_3.2.1    tidyverse_1.3.0 
> [11] phyloseq_1.28.0  breakaway_4.6.14
> 
> loaded via a namespace (and not attached):
>   [1] readxl_1.3.1              backports_1.1.5           plyr_1.8.4               
>   [4] igraph_1.2.4.1            lazyeval_0.2.2            splines_3.6.1            
>   [7] crosstalk_1.0.0           usethis_1.5.1             inline_0.3.15            
>  [10] rstantools_2.0.0          digest_0.6.22             foreach_1.4.7            
>  [13] htmltools_0.4.0           rsconnect_0.8.15          magrittr_1.5             
>  [16] memoise_1.1.0             cluster_2.1.0             doParallel_1.0.15        
>  [19] remotes_2.1.0             Biostrings_2.52.0         modelr_0.1.5             
>  [22] matrixStats_0.55.0        xts_0.11-2                prettyunits_1.0.2        
>  [25] colorspace_1.4-1          rvest_0.3.5               haven_2.2.0              
>  [28] xfun_0.11                 callr_3.3.2               crayon_1.3.4             
>  [31] jsonlite_1.6              RcppArmadillo_0.9.800.1.0 lme4_1.1-21              
>  [34] zeallot_0.1.0             survival_3.1-7            zoo_1.8-6                
>  [37] iterators_1.0.12          ape_5.3                   glue_1.3.1               
>  [40] gtable_0.3.0              zlibbioc_1.30.0           XVector_0.24.0           
>  [43] sjmisc_2.8.2              pkgbuild_1.0.6            rstan_2.19.2             
>  [46] Rhdf5lib_1.6.0            BiocGenerics_0.30.0       abind_1.4-5              
>  [49] scales_1.1.0              DBI_1.0.0                 data.tree_0.7.11         
>  [52] miniUI_0.1.1.1            Rcpp_1.0.3                xtable_1.8-4             
>  [55] bold_0.9.0                StanHeaders_2.19.0        DT_0.10                  
>  [58] stats4_3.6.1              htmlwidgets_1.5.1         httr_1.4.1               
>  [61] threejs_0.3.1             ellipsis_0.3.0            loo_2.1.0                
>  [64] pkgconfig_2.0.3           reshape_0.8.8             dbplyr_1.4.2             
>  [67] crul_0.9.0                later_1.0.0               tidyselect_0.2.5         
>  [70] rlang_0.4.1               reshape2_1.4.3            munsell_0.5.0            
>  [73] cellranger_1.1.0          tools_3.6.1               cli_1.1.0                
>  [76] generics_0.0.2            ade4_1.7-13               sjlabelled_1.1.1         
>  [79] devtools_2.2.1            broom_0.5.2               ggridges_0.5.1           
>  [82] fastmap_1.0.1             evaluate_0.14             biomformat_1.12.0        
>  [85] hablar_0.2.0              processx_3.4.1            knitr_1.26               
>  [88] fs_1.3.1                  packrat_0.5.0             nlme_3.1-142             
>  [91] mime_0.7                  rstanarm_2.19.2           taxize_0.9.91            
>  [94] xml2_1.2.2                shinythemes_1.1.2         compiler_3.6.1           
>  [97] bayesplot_1.7.0           rstudioapi_0.10           curl_4.2                 
> [100] testthat_2.3.0            reprex_0.3.0              stringi_1.4.3            
> [103] ps_1.3.0                  desc_1.2.0                lattice_0.20-38          
> [106] Matrix_1.2-17             grateful_0.0.2            markdown_1.1             
> [109] nloptr_1.2.1              shinyjs_1.0               vegan_2.5-6              
> [112] permute_0.9-5             multtest_2.40.0           vctrs_0.2.0              
> [115] pillar_1.4.2              lifecycle_0.1.0           BiocManager_1.30.10      
> [118] checkpoint_0.4.7          data.table_1.12.6         insight_0.7.0            
> [121] httpuv_1.5.2              R6_2.4.1                  promises_1.1.0           
> [124] gridExtra_2.3             IRanges_2.18.1            sessioninfo_1.1.1        
> [127] codetools_0.2-16          gtools_3.8.1              colourpicker_1.0         
> [130] boot_1.3-23               MASS_7.3-51.4             assertthat_0.2.1         
> [133] pkgload_1.0.2             rhdf5_2.28.0              rprojroot_1.3-2          
> [136] withr_2.1.2               httpcode_0.2.0            shinystan_2.5.0          
> [139] S4Vectors_0.22.0          mgcv_1.8-31               parallel_3.6.1           
> [142] hms_0.5.2                 grid_3.6.1                minqa_1.2.4              
> [145] rmarkdown_1.17            base64enc_0.1-3           shiny_1.4.0              
> [148] Biobase_2.44.0            lubridate_1.7.4           dygraphs_1.1.1.6 


`devtools::install_github("adw96/breakaway", force=TRUE, build_vignettes = TRUE)`
> Downloading GitHub repo adw96/breakaway@master
> Skipping 1 packages not available: phyloseq
> ✔  checking for file ‘/private/var/folders/4g/4wpmdzbd7tj0cwctcd99wz680000gp/T/RtmpJfc9KK/remotes6b71160a4613/adw96-breakaway-1c1215c/DESCRIPTION’ (355ms)
> ─  preparing ‘breakaway’:
> ✔  checking DESCRIPTION meta-information ...
> ─  installing the package to build vignettes
> Registered S3 method overwritten by 'xts':
>   method     from
>   as.zoo.xts zoo 
> ✔  creating vignettes (2m 13.7s)
> ─  excluding invalid files
>    Subdirectory 'R' contains invalid file names:
>      ‘.-package.R’
> ─  checking for LF line-endings in source and make files and shell scripts
> ─  checking for empty or unneeded directories
> ─  looking to see if a ‘data/datalist’ file should be added
> ─  building ‘breakaway_4.6.14.tar.gz’
>    
> * installing *source* package ‘breakaway’ ...
> ** using staged installation
> ** R
> ** data
> *** moving datasets to lazyload DB
> ** inst
> ** byte-compile and prepare package for lazy loading
> ** help
> *** installing help indices
> *** copying figures
> ** building package indices
> ** installing vignettes
> ** testing if installed package can be loaded from temporary location
> ** testing if installed package can be loaded from final location
> ** testing if installed package keeps a record of temporary installation path
> * DONE (breakaway)

`library(breakaway)`
`vignette("intro-diversity-estimation")`   # this was successful
`data("toy_otu_table")`
`build_frequency_count_tables(toy_otu_table)`
> Error in build_frequency_count_tables(toy_otu_table) : 
>   could not find function "build_frequency_count_tables"

**Comment by adw96** [comment]
@paulinetrinh and @bryandmartin  — could you please see if you can reproduce @dougwyu ‘s error, since I cannot. Thanks!! 😺

**Comment by dougwyu** [comment]
Clicking on any command in the breakaway help page produces this:

> Error in fetch(key) : lazy-load database '/Library/Frameworks/R.framework/Versions/3.6/Resources/library/breakaway/help/breakaway.rdb' is corrupt

**Comment by adw96** [comment]
I recommend closing your R session, optionally restarting your computer, creating a new RStudio project for whatever you're working on (or opening up your RStudio project), and running the commands again. This typically fixes corrupt rdb's.

**Comment by dougwyu** [comment]
Thanks.  that worked.  it's strange that it didn't previously, since i had been happily installing other packages from source.
