### ISSUE TITLE
what is exactly is breakaway doing when it chooses poisson/neg. binomial?

### ISSUE THREAD

**Issue by slhogle** [adw96/breakaway#74]
Hi Amy,

Breakaway has selected mixed poisson or negative binomial models for all my samples. I have the same type of low-diversity dataset as in #63 

Can you explain a little bit about what is going on behind the scenes when breakaway uses these models? Does the algorithm still perform an estimate using frequency count ratios or is it just reverting to the 'classic' approach with frequency counts? 

Sorry if this was already explained in Willis 2015 - feel free to just point me to the relevant paragraph in the paper.

thanks!!
-shane

**Comment by adw96** [comment]
Thanks for clarifying, Shane! 

If a frequency count ratio approach is not possible, breakaway attempts to fit the Chao-Bunge estimator described here: https://www.ncbi.nlm.nih.gov/pubmed/12229987 

The Chao-Bunge estimator is based on a negative binomial model, and it's a moment-based estimator.  

That estimator doesn't necessarily converge. If it doesn't converge, breakaway fits a Poisson model using  maximum likelihood.  

Let me know if this doesn't answer your question -- I'm happy to provide more details!

**Comment by slhogle** [comment]
thanks! that's what I was thinking, so good to have it confirmed :)
