### ISSUE TITLE
Comparing singificance of factors, not factor levels

### ISSUE THREAD

**Issue by liisaveerus** [adw96/breakaway#76]
Dear Amy,

Happy New Year! As my background is more in the evolutionary biology side, it is very common to also report in papers, e.g. chi-squared estimates of fixed effects groups, and then explain specifics, like your model$table output shows (regression model-like output).

Is there a way to tackle this with breakaway, e.g. like Anova(model,...) can be used for many different model types across packages?

For clarification, I model betta_random with breakaway estimates + errors, no factor interactions, and a single random effect:

model <- betta_random(chats = dat$estimate,
                                ses = dat$error,
                                X = model.matrix(~Organ+Health.Status+Age, data = dat),
                                groups=dat$Bird.ID) 

Thank you :)!

**Comment by adw96** [comment]
Hi @liisaveerus -- I'll try to help. You need a null model (reduced model) to compare your fitted model against; what null model do you want to compare to? 

If the null model you want to test is an intercept-only model, this you can use `my_model$global` to get this information. The first number is the test statistic and the second number is a p-value for testing the null that $\beta_1=...=\beta_p=0$. 

Hope this helps!

**Comment by liisaveerus** [comment]
Thank you, Amy, this makes sense :)!

Would you mind (1) specifying what test statistic is used for the model$global output and (2) whether it is also possible to test the significance of different beta estimates, i.e. change the null model to something other than just an intercept-only model, e.g. compare Diversity=Sample Type + Health Status to a simplified, nested model Diversity=Sample Type to reveal the effect of adding Health Status to the model?

Many thanks for your help!
