### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by genomewalker** [adw96/breakaway#8]
Hi
I started to play around with _breakaway_ and when reading the _Getting started_ document and in the section *Estimating alpha diversity*:

> BTW, you can use the above to look sample size variability as well. If you have very different numbers of reads across samples, this can introduce additional variability. Let’s look at the distribution of reads in the current dataset.

The code in the documentation is:

`ns <- unlist(lapply(frequencytablelist, function(x) sum(x[,2])))`

Maybe I am missing something, but this is just summing up the frequencies;  shouldn't it be

`ns <- unlist(lapply(frequencytablelist, function(x) sum(x[,1]*x[,2])))` 

to get the number of reads per sample?

Many thanks for developing such great methods!!!
Antonio

**Comment by adw96** [comment]
You're totally right -- thank you for spotting this! I will fix it on the next push enclose this issue then.

This is very helpful -- many thanks!

**Comment by genomewalker** [comment]
Many thanks!
