### ISSUE TITLE
Installing Vignettes, needs corncob

### ISSUE THREAD

**Issue by ramongallego** [adw96/breakaway#80]
Hi there,

I cannot find the vignettes from the package. I reinstalled the package forcing them it build it with 
`devtools::install_github("adw96/breakaway", build_vignettes = T, force = T)`

Seems like the package `corncob` needs to be installed first to create the vignettes, so maybe add it to the list of required packages?
![image](https://user-images.githubusercontent.com/15640943/73566816-ae751000-4419-11ea-8f20-e11ce71d2401.png)

**Comment by adw96** [comment]
Thanks for letting us know! In the meantime, if you install corncob from [here](https://github.com/bryandmartin/corncob/), does it work?

I will fix this now.

**Comment by adw96** [comment]
Ah yes, we went back and forth on this one a while ago and made the conscious decision not to have it as a dependency; it's listed as `Suggested` only. There are a couple of reasons for this but basically we only use corncob for a dataset in a vignette, and it's not even the main vignette.  We are therefore not going to make a typical user require corncob. 

So run 

`devtools::install_github("bryandmartin/corncob")`

and you shouldn't have problems.

**Comment by ramongallego** [comment]
Thanks! It's just that until I installed corncob it did not let me load any
of the vignettes -

I am looking at the vignettes now :)
