### ISSUE TITLE
Standard errors equal zero

### ISSUE THREAD

**Issue by icar-y** [adw96/breakaway#83]
Hi there, 

I've been trying to use breakaway and DivNet to analyse my microbiome data. However,  I am having issues with the outputs. 
My data:

![Ps object](https://user-images.githubusercontent.com/59726926/78650425-30bcfd00-78bf-11ea-9076-c106f7753ee9.png)

As you see, the estimates, standard errors, and the lower and upper bounds don't look good. Most of the standard errors (90% of my samples) equal to zero.  And this happens when using both the sample_richness and breakaway. I got the following warning:

![Untitled picture](https://user-images.githubusercontent.com/59726926/78649227-72e53f00-78bd-11ea-87bd-47bfb47df80e.png)

The plot looks like this:
![Plot breakaway](https://user-images.githubusercontent.com/59726926/78649791-39610380-78be-11ea-8d4f-620424fec6bf.png)

These results don't make sense to me. I am not sure what I am doing wrong or the reasons behind this. Many thanks in advance!

This is my session info:
![Session info](https://user-images.githubusercontent.com/59726926/78649927-75946400-78be-11ea-830f-0f119ed20096.png)

**Comment by adw96** [comment]
Hi @icar-y -- nothing looks wrong to me here! What you're seeing here is that your data suggests that you have very few unobserved taxa... which is unsurprising given that you're analyzing data at the phylum level! It's pretty rare to have more than one or two phylum unobserved, in my experience. 

The output of breakaway should be interpreted in the context of the input -- so if you put in phylum level counts, phylum level diversity will be estimated. 

I suspect that if you were estimating the number of unobserved species/ASVs/OTUs, you would see significantly more unobserved diversity and significantly higher error bars. 

I hope that helps and if you have any more issues feel free to reopen this issue.

Amy
