### ISSUE TITLE
how to select the best richness index for my data?

### ISSUE THREAD

**Issue by guangingmai** [adw96/breakaway#87]
Hi, i am new in the `breakaway` package. I find that there are a lot of richness index in `breakaway` package and i don't know how to choose the best (or namely the optimal) richness index for my dataset. Can the author give me some suggestions? Thank you.

**Comment by adw96** [comment]
Hi @guangingmai . I recommend using the function `breakaway` to estimate species richness. I think it's the optimal method in the package. Cheers, Amy

**Comment by guangingmai** [comment]
Thank you for your reply.
