### ISSUE TITLE
plotting group means and errors

### ISSUE THREAD

**Issue by nicholascdove** [adw96/breakaway#96]
Instead of plotting the estimate and error for individual samples, how should one plot group means and errors? I understand that I can extract group means using the betta function, but I'm unsure of how to extract the error from groups that are not the intercept. I could probably sequentially dummy code the variables, so that each would be the intercept, but I wonder if there is an easier way.

**Comment by ailurophilia** [comment]
Hi @nicholascdove – sorry for the delay getting back to you. The newest version of breakaway now includes a function, `betta_lincom`, that will give you means and confidence intervals for arbitrary linear combinations of fixed effects in your model. There's an example given in the discussion of [issue 111](https://github.com/adw96/breakaway/issues/111), and the the hypothesis testing vignette for breakaway (v 4.7.4) also discusses this function. Hope this helps!
